Reference.create(name: 'apple')
Reference.create(name: 'computer')
Reference.create(name: 'forks')

Movement.create(comming_in: true, quantity: 2,  reference_id: 1)
Movement.create(comming_in: true, quantity: 1,  reference_id: 1)
Movement.create(comming_in: true, quantity: 5,  reference_id: 2)
Movement.create(comming_in: false, quantity: 2,  reference_id: 1)
Movement.create(comming_in: true, quantity: 1,  reference_id: 3)
Movement.create(comming_in: true, quantity: 3,  reference_id: 3)
Movement.create(comming_in: false, quantity: 2,  reference_id: 3)
